// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlAsiY_scl_TKV-PYFU645zvfGOpU-Wrw',
    appId: '1:553693361241:web:087bf9306d00653b10ed48',
    messagingSenderId: '553693361241',
    projectId: 'examen-programovil',
    authDomain: 'examen-programovil.firebaseapp.com',
    storageBucket: 'examen-programovil.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyzpZPJw4pSJk2en8kBnLXR4DLskSHTa0',
    appId: '1:553693361241:android:25ec8e5b5b517aaa10ed48',
    messagingSenderId: '553693361241',
    projectId: 'examen-programovil',
    storageBucket: 'examen-programovil.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKtaS-TSE-NrQTZV7VH1iDdhHbFtrzK7A',
    appId: '1:553693361241:ios:627af9b8a33042f410ed48',
    messagingSenderId: '553693361241',
    projectId: 'examen-programovil',
    storageBucket: 'examen-programovil.appspot.com',
    iosBundleId: 'com.example.examenFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKtaS-TSE-NrQTZV7VH1iDdhHbFtrzK7A',
    appId: '1:553693361241:ios:627af9b8a33042f410ed48',
    messagingSenderId: '553693361241',
    projectId: 'examen-programovil',
    storageBucket: 'examen-programovil.appspot.com',
    iosBundleId: 'com.example.examenFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlAsiY_scl_TKV-PYFU645zvfGOpU-Wrw',
    appId: '1:553693361241:web:c8dd39667be4faf110ed48',
    messagingSenderId: '553693361241',
    projectId: 'examen-programovil',
    authDomain: 'examen-programovil.firebaseapp.com',
    storageBucket: 'examen-programovil.appspot.com',
  );
}
